### ISSUE TITLE
Что такое период?

### ISSUE THREAD

**Issue by Timurunrun** [kesha1225/DnevnikRuAPI#12]
В документации вы указали о
![image](https://user-images.githubusercontent.com/61642612/195369685-a23d196b-2a7b-48fb-8a79-e2c6a2119a2d.png). Где найти код периода?

**Comment by lukintrees** [comment]
В поле «Период» указывается период времени, за который необходимо получить оценки.
Ожидается временная метка Unix (секунды с 1 января 1970 г.) для:

Начало периода
Конец периода

Так, например, чтобы получить оценки с 1 января 2020 года по 31 марта 2020 года, вы можете использовать:
?period[from]=1577808000&period[to]=1585740799

Это временные метки Unix для этих дат.
Таким образом, это позволяет вам указать настраиваемый диапазон дат для получения оценок, а не только все оценки или оценки за определенный семестр/год.
