### ISSUE TITLE
Измени названия

### ISSUE THREAD

**Issue by 0susboy0** [kesha1225/DnevnikRuAPI#5]
**прошу умоляю.. ради красивого кода.. измени названия методов, а то параша какая-то**

**Comment by kesha1225** [comment]
лень.........

**Comment by 0susboy0** [comment]
какое сука лень? просто мерзоСть, ничего не понятно... **половину названий можно сократить вдвое**

**Comment by kesha1225** [comment]
Тогда будет непонятно че они делают

**Comment by 0susboy0** [comment]
ладно сУкА, сейчас перепишу... уговорил

**Comment by 0susboy0** [comment]
умница, теперь все красиво 😉
