### ISSUE TITLE
Ошибка authorizationFailed при логине с правильными данными

### ISSUE THREAD

**Issue by SNESEAR** [kesha1225/DnevnikRuAPI#7]
Хотел попробовать pydnevnikruapi.dnevnik, но он при выполнении кода выдаёт:
{'type': 'authorizationFailed', 'description': "Can't authorize"}
P. S. (логин и пароль проверил, правильные)
Подскажите пожалуйста, может я делаю что-то не так?

```
from pydnevnikruapi.dnevnik import dnevnik

log = 'login'
pas = 'password'

dn = dnevnik.DiaryAPI(login=log, password=pas)

print(dn.get_classmates())
```

**Comment by kesha1225** [comment]
произошел фикс))
